import numpy as np

def divider():
    print("=" * 56)

def explain_best_model(best_name):
    if 'Decision Tree' in best_name or 'Tree' in best_name:
        return ("Decision Tree performed best because your dataset likely has "
                "non-linear patterns and complex feature interactions. "
                "Tree-based models handle these better than linear models.")
    if 'Logistic' in best_name or 'Linear' in best_name:
        return ("Linear model performed best which suggests your data has a "
                "relatively linear relationship between features and target. "
                "This also means your data is clean and well-structured.")
    if 'KNN' in best_name:
        return ("KNN performed best which suggests your data has strong local "
                "patterns — similar data points tend to have similar outcomes.")
    return f"{best_name} achieved the highest score on your dataset."

def get_feature_importance(best_result, feature_cols):
    model      = best_result['model']
    model_name = type(model).__name__
    if 'Tree' in model_name and hasattr(model, 'feature_importances_'):
        imp = model.feature_importances_
        if len(imp) == len(feature_cols):
            idx  = np.argmax(imp)
            return feature_cols[idx], round(imp[idx] * 100, 1)
    return None, None

def assess_data_quality(analysis):
    issues = []
    if analysis['total_missing'] > 0:
        issues.append(f"{analysis['total_missing']} missing values filled")
    if analysis['duplicates'] > 0:
        issues.append(f"{analysis['duplicates']} duplicates removed")
    if 'imbalance' in analysis['balance_status'].lower():
        issues.append("class imbalance present — results may be biased toward majority class")
    return ("Excellent — no preprocessing issues found." if not issues
            else "Handled: " + ", ".join(issues) + ".")

def assess_accuracy(score, problem_type):
    if problem_type == 'classification':
        if score >= 95:
            return (f"Very high accuracy ({score}%). "
                    "WARNING: Possible overfitting. Test with new unseen data to confirm.")
        elif score >= 80:
            return f"Good accuracy ({score}%). Model is performing well."
        elif score >= 65:
            return f"Moderate accuracy ({score}%). Consider more data or better features."
        else:
            return (f"Low accuracy ({score}%). Possible reasons: insufficient data, "
                    "irrelevant features, or wrong problem setup.")
    else:
        if score >= 85:
            return f"Strong R2 score ({score}%). Model explains the data well."
        elif score >= 60:
            return f"Moderate R2 ({score}%). Room for improvement with more features."
        else:
            return (f"Low R2 ({score}%). Model is struggling. "
                    "Consider more relevant features or review data quality.")

def run_insights(best_name, best_result, feature_cols, analysis, problem_type):
    divider()
    print("  MODULE 5 — AI INSIGHTS")
    divider()

    score = best_result['score']

    print(f"\n  Best model     : {best_name} ({score}%)\n")

    explanation = explain_best_model(best_name)
    print(f"  Why it won     : {explanation}\n")

    feat, imp = get_feature_importance(best_result, feature_cols)
    if feat:
        print(f"  Key factor     : Most influential feature is")
        print(f"                   '{feat}' ({imp}% importance)\n")
    else:
        print(f"  Key factor     : Feature importance not available for {best_name}.\n")

    quality = assess_data_quality(analysis)
    print(f"  Data quality   : {quality}\n")

    note = assess_accuracy(score, problem_type)
    print(f"  Assessment     : {note}\n")

    print(f"  Recommendation : Use {best_name} for predictions on")
    print(f"                   new data from this same domain.\n")

    divider()
    print("  META WARNING")
    divider()
    print("  This analysis is generated by an automated ML")
    print("  system. It carries its own uncertainty and can")
    print("  be wrong. Results depend on data quality.")
    print("  Always verify with domain knowledge and human")
    print("  judgment before making any real world decision.")
    print("  No automated system should be trusted blindly.")
    divider()
    print()